new-session -s default -A
#
# for pbcopy
# set-option -g default-command "reattach-to-user-namespace -l bash"
#
# auto window title
set-window-option -g automatic-rename on
set-option -g set-titles on
#
# monitor
setw -g monitor-activity on
set-option -gw window-status-activity-style fg=green
#
# turn off delay on escape key
set -sg escape-time 0
#
set -g status-bg blue
set -g status-fg white

set-option -g status-justify centre
set-window-option -g window-status-format         '#[fg=cyan,dim]#I#[fg=blue]:#[default]#W#[fg=grey,dim]'
set-window-option -g window-status-current-format '#[fg=cyan]#I#[fg=blue]:#[fg=white,bold,reverse]#W#[default]'


set -g window-status-current-bg white
set -g window-status-current-fg blue
set -g window-status-current-attr bold
#
set -g status-interval 1
set -g status-left-length 30
set -g status-left '#[fg=cyan](#S)'
#set -g status-right '#[fg=yellow]#(cut -d " " -f 1-3 /proc/loadavg)#[default] %Y-%m-%d %H:%M:%S#[default]'
#set -g status-right '(#(cut -d " " -f 1-3 /proc/loadavg)) %Y-%m-%d %H:%M:%S'
set -g status-right-length 66
set -g status-right-fg yellow
set-option -g status-right '#(/usr/bin/tmux-mem --format ":currentBytes [#[fg=:color]:spark#[default]] #[fg=:color]:percent#[default]") #[fg=cyan](#(~/bin/memused.sh))#[default] #(/usr/bin/tmux-cpu --format "[#[fg=:color]:spark#[default]] #[fg=:color]:percent#[default] #[fg=white,bold]:load#[default]") %Y-%m-%d %H:%M:%S'

#set -g pane-border-bg blue
#set -g pane-border-fg blue
#set -g pane-active-border-bg cyan
#set -g pane-active-border-fg cyan
#
bind-key h select-pane -L
bind-key j select-pane -D
bind-key k select-pane -U
bind-key l select-pane -R
#
bind-key a setw synchronize-panes

set-window-option -g xterm-keys on
set-window-option -g mode-keys vi
#set-window-option -g mouse-select-pane on

set -g prefix  C-b
#set -g prefix2 C-a

#### COLOUR (Solarized 256)

# default statusbar colors
set-option -g status-bg colour235 #base02
set-option -g status-fg cyan
set-option -g status-attr default

# default window title colors
set-window-option -g window-status-fg colour244 #base0
set-window-option -g window-status-bg default
#set-window-option -g window-status-attr dim

# active window title colors
set-window-option -g window-status-current-fg white
set-window-option -g window-status-current-bg default
#set-window-option -g window-status-current-attr bright

# pane border
set-option -g pane-border-fg colour235 #base02
set-option -g pane-active-border-fg colour240 #base01

# message text
set-option -g message-bg colour235 #base02
set-option -g message-fg yellow

# pane number display
set-option -g display-panes-active-colour colour33 #blue
set-option -g display-panes-colour yellow

# clock
set-window-option -g clock-mode-colour colour64 #green
#set-option -g status-position top
set -g default-terminal "xterm-256color"

set-option -g history-limit 10000

bind R source-file ~/.tmux.conf \; display-message "  Config reloaded..".
bind C-t command-prompt 'new-window %%'
bind C-s command-prompt 'new-window -n %1 ssh %1'
bind C-p send-keys '/bin/grep -q "alias pat=" ~/.bash_profile || echo "alias pat=\"puppet agent -t 2>&1 | tee ~/pat.out\"" >> ~/.bash_profile && . ~/.bash_profile ; /bin/grep -q "alias patd=" ~/.bash_profile || echo "alias patd=\"puppet agent -t --debug 2>&1 | tee ~/pat.out\"" >> ~/.bash_profile && . ~/.bash_profile'


new-window -k -t 0 -d htop
