# [window]
# opacity = 0.93

[shell]
args = ['--login']
program = "/usr/bin/zsh"

[font.normal]
family = "SauceCodePro Nerd Font Mono"

[font]
size = 12

[window.dimensions]
columns = 140
lines = 60

