alias diff='diff -u'
alias install='sudo yum install'
alias whatprovides='sudo yum whatprovides'
alias puppet-lint='puppet-lint --no-autoloader_layout-check --no-hard_tabs-check --no-trailing_whitespace-check --no-2sp_soft_tabs-check --no-single_quote_string_with_variables-check'
alias gvim='gvim -p'
alias cdpe='cd ~/svn/systems/trunk/puppet/environments/'
alias cdpl='cd ~/svn/systems/trunk/puppet/environments/lab/'
alias cdpd='cd ~/svn/systems/trunk/puppet/environments/development/'
alias cdps='cd ~/svn/systems/trunk/puppet/environments/staging/'
alias cdpp='cd ~/svn/systems/trunk/puppet/environments/production/'
alias environments='cd ~/svn/systems/trunk/puppet/environments/'
alias meld='GTK_THEME=Greybird meld'
alias svnmeld='GTK_THEME=Greybird svn --diff-cmd meld diff'
alias ssh='ssh -q'
alias batterysaver='~/bin/setbrightness 60 && ~/bin/cpu s'
alias ppv='puppet parser validate'
alias edit='sublime_text -n '
alias sup='svn up'
alias s.gpg='gpg -d ~/.crypt/systems.gpg'
alias pssh='pssh -x -q -A -o out -e err'
alias pscp='pscp.pssh -x -q -A -o out -e err'
alias vpnc='sudo vpnc'
alias vpnc-disconnect='sudo vpnc-disconnect'
alias atom='atom -n'
alias t='terminator &'
alias a='atom -n ~/svn/systems/trunk/puppet/environments'
alias b=brightness
alias t='tmux a || tmux'
